# Generated by Django 4.1.7 on 2023-04-03 17:22

import django.core.validators
from django.db import migrations, models
import obieg.models


class Migration(migrations.Migration):

    dependencies = [
        ('obieg', '0002_alter_document_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=obieg.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
