# Generated by Django 4.2 on 2023-04-04 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('obieg', '0003_alter_document_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zuzycie_cel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cel', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='data_dok',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ksieg_ma1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='ksieg_ma2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='ksieg_ma3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='ksieg_ma4',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='ksieg_wn1',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='ksieg_wn2',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='ksieg_wn3',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='ksieg_wn4',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='zuzyto_cel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='obieg.zuzycie_cel'),
            preserve_default=False,
        ),
    ]
