# Generated by Django 4.2 on 2023-04-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obieg', '0005_alter_document_zuzyto_cel_delete_zuzycie_cel'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='rodzaj_dokumentu',
            field=models.CharField(choices=[(1, 'skan'), (2, 'elektroniczny')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
